/**
* DO NOT EDIT THIS FILE.
* See the following change record for more information,
* https://www.drupal.org/node/2815083
* @preserve
**/
var _this = this;

var submittedFormId = '';

function recaptchaCallback() {
  document.getElementById(submittedFormId).submit();
}

(function ($, Drupal) {
  Drupal.behaviors.invisibleRecaptcha = {
    attach: function attach(context) {
      function validateInvisibleCaptcha($form) {
        submittedFormId = $form.attr('id');
        grecaptcha.execute();
      }
      $('form', context).each(function () {
        var $form = $(_this);

        if ($form.find('.g-recaptcha[data-size="invisible"]').length) {
          $form.find('input[type="submit"]').click(function (e) {
            e.preventDefault();
            validateInvisibleCaptcha($form);
          });
        }
      });
    }
  };
})(jQuery, Drupal);