invisible_recaptcha.recaptcha_points:
  type: config_object
  label: 'Invisible recaptcha check'
  mapping:
    forms_ids:
      type: sequence
      label: 'The ids of the forms.'
      sequence:
        type: string
        label: 'The id of the form.'
